package com.jxufe.liuyf.fsv.common.bean;

import java.util.ArrayList;
import java.util.List;

public class CfgBusinessCodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public CfgBusinessCodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBusicodeIsNull() {
            addCriterion("BUSICODE is null");
            return (Criteria) this;
        }

        public Criteria andBusicodeIsNotNull() {
            addCriterion("BUSICODE is not null");
            return (Criteria) this;
        }

        public Criteria andBusicodeEqualTo(String value) {
            addCriterion("BUSICODE =", value, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeNotEqualTo(String value) {
            addCriterion("BUSICODE <>", value, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeGreaterThan(String value) {
            addCriterion("BUSICODE >", value, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeGreaterThanOrEqualTo(String value) {
            addCriterion("BUSICODE >=", value, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeLessThan(String value) {
            addCriterion("BUSICODE <", value, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeLessThanOrEqualTo(String value) {
            addCriterion("BUSICODE <=", value, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeLike(String value) {
            addCriterion("BUSICODE like", value, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeNotLike(String value) {
            addCriterion("BUSICODE not like", value, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeIn(List<String> values) {
            addCriterion("BUSICODE in", values, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeNotIn(List<String> values) {
            addCriterion("BUSICODE not in", values, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeBetween(String value1, String value2) {
            addCriterion("BUSICODE between", value1, value2, "busicode");
            return (Criteria) this;
        }

        public Criteria andBusicodeNotBetween(String value1, String value2) {
            addCriterion("BUSICODE not between", value1, value2, "busicode");
            return (Criteria) this;
        }

        public Criteria andInterfaceeIsNull() {
            addCriterion("INTERFACEE is null");
            return (Criteria) this;
        }

        public Criteria andInterfaceeIsNotNull() {
            addCriterion("INTERFACEE is not null");
            return (Criteria) this;
        }

        public Criteria andInterfaceeEqualTo(String value) {
            addCriterion("INTERFACEE =", value, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeNotEqualTo(String value) {
            addCriterion("INTERFACEE <>", value, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeGreaterThan(String value) {
            addCriterion("INTERFACEE >", value, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeGreaterThanOrEqualTo(String value) {
            addCriterion("INTERFACEE >=", value, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeLessThan(String value) {
            addCriterion("INTERFACEE <", value, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeLessThanOrEqualTo(String value) {
            addCriterion("INTERFACEE <=", value, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeLike(String value) {
            addCriterion("INTERFACEE like", value, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeNotLike(String value) {
            addCriterion("INTERFACEE not like", value, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeIn(List<String> values) {
            addCriterion("INTERFACEE in", values, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeNotIn(List<String> values) {
            addCriterion("INTERFACEE not in", values, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeBetween(String value1, String value2) {
            addCriterion("INTERFACEE between", value1, value2, "interfacee");
            return (Criteria) this;
        }

        public Criteria andInterfaceeNotBetween(String value1, String value2) {
            addCriterion("INTERFACEE not between", value1, value2, "interfacee");
            return (Criteria) this;
        }

        public Criteria andMothodIsNull() {
            addCriterion("MOTHOD is null");
            return (Criteria) this;
        }

        public Criteria andMothodIsNotNull() {
            addCriterion("MOTHOD is not null");
            return (Criteria) this;
        }

        public Criteria andMothodEqualTo(String value) {
            addCriterion("MOTHOD =", value, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodNotEqualTo(String value) {
            addCriterion("MOTHOD <>", value, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodGreaterThan(String value) {
            addCriterion("MOTHOD >", value, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodGreaterThanOrEqualTo(String value) {
            addCriterion("MOTHOD >=", value, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodLessThan(String value) {
            addCriterion("MOTHOD <", value, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodLessThanOrEqualTo(String value) {
            addCriterion("MOTHOD <=", value, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodLike(String value) {
            addCriterion("MOTHOD like", value, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodNotLike(String value) {
            addCriterion("MOTHOD not like", value, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodIn(List<String> values) {
            addCriterion("MOTHOD in", values, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodNotIn(List<String> values) {
            addCriterion("MOTHOD not in", values, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodBetween(String value1, String value2) {
            addCriterion("MOTHOD between", value1, value2, "mothod");
            return (Criteria) this;
        }

        public Criteria andMothodNotBetween(String value1, String value2) {
            addCriterion("MOTHOD not between", value1, value2, "mothod");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 19 20:50:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}