package com.jxufe.liuyf.fsv.common.bean;

import com.jxufe.liuyf.fsv.common.AbstractCacheTable;
import com.jxufe.liuyf.fsv.common.CacheIndex;
import org.codehaus.jackson.annotate.JsonIgnore;

public class CfgPageContent extends AbstractCacheTable implements CacheIndex{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PAGE_CONTENT.PAGE_URL
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    private String pageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PAGE_CONTENT.PAGE_CATEGORY
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    private String pageCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PAGE_CONTENT.CONTENT_LOCATION
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    private String contentLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PAGE_CONTENT.CONTENT_TYPE
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PAGE_CONTENT.CONTENT_DESCRIPTION
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    private String contentDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CFG_PAGE_CONTENT.THE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    private String theContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PAGE_CONTENT.PAGE_URL
     *
     * @return the value of CFG_PAGE_CONTENT.PAGE_URL
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public String getPageUrl() {
        return pageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PAGE_CONTENT.PAGE_URL
     *
     * @param pageUrl the value for CFG_PAGE_CONTENT.PAGE_URL
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl == null ? null : pageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PAGE_CONTENT.PAGE_CATEGORY
     *
     * @return the value of CFG_PAGE_CONTENT.PAGE_CATEGORY
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public String getPageCategory() {
        return pageCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PAGE_CONTENT.PAGE_CATEGORY
     *
     * @param pageCategory the value for CFG_PAGE_CONTENT.PAGE_CATEGORY
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void setPageCategory(String pageCategory) {
        this.pageCategory = pageCategory == null ? null : pageCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PAGE_CONTENT.CONTENT_LOCATION
     *
     * @return the value of CFG_PAGE_CONTENT.CONTENT_LOCATION
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public String getContentLocation() {
        return contentLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PAGE_CONTENT.CONTENT_LOCATION
     *
     * @param contentLocation the value for CFG_PAGE_CONTENT.CONTENT_LOCATION
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void setContentLocation(String contentLocation) {
        this.contentLocation = contentLocation == null ? null : contentLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PAGE_CONTENT.CONTENT_TYPE
     *
     * @return the value of CFG_PAGE_CONTENT.CONTENT_TYPE
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PAGE_CONTENT.CONTENT_TYPE
     *
     * @param contentType the value for CFG_PAGE_CONTENT.CONTENT_TYPE
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PAGE_CONTENT.CONTENT_DESCRIPTION
     *
     * @return the value of CFG_PAGE_CONTENT.CONTENT_DESCRIPTION
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public String getContentDescription() {
        return contentDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PAGE_CONTENT.CONTENT_DESCRIPTION
     *
     * @param contentDescription the value for CFG_PAGE_CONTENT.CONTENT_DESCRIPTION
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void setContentDescription(String contentDescription) {
        this.contentDescription = contentDescription == null ? null : contentDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CFG_PAGE_CONTENT.THE_CONTENT
     *
     * @return the value of CFG_PAGE_CONTENT.THE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public String getTheContent() {
        return theContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CFG_PAGE_CONTENT.THE_CONTENT
     *
     * @param theContent the value for CFG_PAGE_CONTENT.THE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void setTheContent(String theContent) {
        this.theContent = theContent == null ? null : theContent.trim();
    }

    @Override
    @JsonIgnore
    public String getIndex() {
        StringBuilder sb = new StringBuilder();
        sb.append(getFullClassName(this)).append(pageUrl).append("_").append(pageCategory).append("_").append(contentLocation).append("_").append(contentType);
        return sb.toString();
    }
}