package com.jxufe.liuyf.fsv.common.bean;

import java.util.ArrayList;
import java.util.List;

public class CfgPageContentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public CfgPageContentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPageUrlIsNull() {
            addCriterion("PAGE_URL is null");
            return (Criteria) this;
        }

        public Criteria andPageUrlIsNotNull() {
            addCriterion("PAGE_URL is not null");
            return (Criteria) this;
        }

        public Criteria andPageUrlEqualTo(String value) {
            addCriterion("PAGE_URL =", value, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlNotEqualTo(String value) {
            addCriterion("PAGE_URL <>", value, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlGreaterThan(String value) {
            addCriterion("PAGE_URL >", value, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("PAGE_URL >=", value, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlLessThan(String value) {
            addCriterion("PAGE_URL <", value, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlLessThanOrEqualTo(String value) {
            addCriterion("PAGE_URL <=", value, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlLike(String value) {
            addCriterion("PAGE_URL like", value, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlNotLike(String value) {
            addCriterion("PAGE_URL not like", value, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlIn(List<String> values) {
            addCriterion("PAGE_URL in", values, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlNotIn(List<String> values) {
            addCriterion("PAGE_URL not in", values, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlBetween(String value1, String value2) {
            addCriterion("PAGE_URL between", value1, value2, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageUrlNotBetween(String value1, String value2) {
            addCriterion("PAGE_URL not between", value1, value2, "pageUrl");
            return (Criteria) this;
        }

        public Criteria andPageCategoryIsNull() {
            addCriterion("PAGE_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andPageCategoryIsNotNull() {
            addCriterion("PAGE_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andPageCategoryEqualTo(String value) {
            addCriterion("PAGE_CATEGORY =", value, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryNotEqualTo(String value) {
            addCriterion("PAGE_CATEGORY <>", value, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryGreaterThan(String value) {
            addCriterion("PAGE_CATEGORY >", value, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("PAGE_CATEGORY >=", value, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryLessThan(String value) {
            addCriterion("PAGE_CATEGORY <", value, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryLessThanOrEqualTo(String value) {
            addCriterion("PAGE_CATEGORY <=", value, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryLike(String value) {
            addCriterion("PAGE_CATEGORY like", value, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryNotLike(String value) {
            addCriterion("PAGE_CATEGORY not like", value, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryIn(List<String> values) {
            addCriterion("PAGE_CATEGORY in", values, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryNotIn(List<String> values) {
            addCriterion("PAGE_CATEGORY not in", values, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryBetween(String value1, String value2) {
            addCriterion("PAGE_CATEGORY between", value1, value2, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andPageCategoryNotBetween(String value1, String value2) {
            addCriterion("PAGE_CATEGORY not between", value1, value2, "pageCategory");
            return (Criteria) this;
        }

        public Criteria andContentLocationIsNull() {
            addCriterion("CONTENT_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andContentLocationIsNotNull() {
            addCriterion("CONTENT_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andContentLocationEqualTo(String value) {
            addCriterion("CONTENT_LOCATION =", value, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationNotEqualTo(String value) {
            addCriterion("CONTENT_LOCATION <>", value, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationGreaterThan(String value) {
            addCriterion("CONTENT_LOCATION >", value, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT_LOCATION >=", value, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationLessThan(String value) {
            addCriterion("CONTENT_LOCATION <", value, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationLessThanOrEqualTo(String value) {
            addCriterion("CONTENT_LOCATION <=", value, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationLike(String value) {
            addCriterion("CONTENT_LOCATION like", value, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationNotLike(String value) {
            addCriterion("CONTENT_LOCATION not like", value, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationIn(List<String> values) {
            addCriterion("CONTENT_LOCATION in", values, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationNotIn(List<String> values) {
            addCriterion("CONTENT_LOCATION not in", values, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationBetween(String value1, String value2) {
            addCriterion("CONTENT_LOCATION between", value1, value2, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentLocationNotBetween(String value1, String value2) {
            addCriterion("CONTENT_LOCATION not between", value1, value2, "contentLocation");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNull() {
            addCriterion("CONTENT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNotNull() {
            addCriterion("CONTENT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andContentTypeEqualTo(String value) {
            addCriterion("CONTENT_TYPE =", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotEqualTo(String value) {
            addCriterion("CONTENT_TYPE <>", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThan(String value) {
            addCriterion("CONTENT_TYPE >", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT_TYPE >=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThan(String value) {
            addCriterion("CONTENT_TYPE <", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThanOrEqualTo(String value) {
            addCriterion("CONTENT_TYPE <=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLike(String value) {
            addCriterion("CONTENT_TYPE like", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotLike(String value) {
            addCriterion("CONTENT_TYPE not like", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeIn(List<String> values) {
            addCriterion("CONTENT_TYPE in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotIn(List<String> values) {
            addCriterion("CONTENT_TYPE not in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeBetween(String value1, String value2) {
            addCriterion("CONTENT_TYPE between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotBetween(String value1, String value2) {
            addCriterion("CONTENT_TYPE not between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionIsNull() {
            addCriterion("CONTENT_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionIsNotNull() {
            addCriterion("CONTENT_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionEqualTo(String value) {
            addCriterion("CONTENT_DESCRIPTION =", value, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionNotEqualTo(String value) {
            addCriterion("CONTENT_DESCRIPTION <>", value, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionGreaterThan(String value) {
            addCriterion("CONTENT_DESCRIPTION >", value, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT_DESCRIPTION >=", value, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionLessThan(String value) {
            addCriterion("CONTENT_DESCRIPTION <", value, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionLessThanOrEqualTo(String value) {
            addCriterion("CONTENT_DESCRIPTION <=", value, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionLike(String value) {
            addCriterion("CONTENT_DESCRIPTION like", value, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionNotLike(String value) {
            addCriterion("CONTENT_DESCRIPTION not like", value, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionIn(List<String> values) {
            addCriterion("CONTENT_DESCRIPTION in", values, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionNotIn(List<String> values) {
            addCriterion("CONTENT_DESCRIPTION not in", values, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionBetween(String value1, String value2) {
            addCriterion("CONTENT_DESCRIPTION between", value1, value2, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andContentDescriptionNotBetween(String value1, String value2) {
            addCriterion("CONTENT_DESCRIPTION not between", value1, value2, "contentDescription");
            return (Criteria) this;
        }

        public Criteria andTheContentIsNull() {
            addCriterion("THE_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andTheContentIsNotNull() {
            addCriterion("THE_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andTheContentEqualTo(String value) {
            addCriterion("THE_CONTENT =", value, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentNotEqualTo(String value) {
            addCriterion("THE_CONTENT <>", value, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentGreaterThan(String value) {
            addCriterion("THE_CONTENT >", value, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentGreaterThanOrEqualTo(String value) {
            addCriterion("THE_CONTENT >=", value, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentLessThan(String value) {
            addCriterion("THE_CONTENT <", value, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentLessThanOrEqualTo(String value) {
            addCriterion("THE_CONTENT <=", value, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentLike(String value) {
            addCriterion("THE_CONTENT like", value, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentNotLike(String value) {
            addCriterion("THE_CONTENT not like", value, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentIn(List<String> values) {
            addCriterion("THE_CONTENT in", values, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentNotIn(List<String> values) {
            addCriterion("THE_CONTENT not in", values, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentBetween(String value1, String value2) {
            addCriterion("THE_CONTENT between", value1, value2, "theContent");
            return (Criteria) this;
        }

        public Criteria andTheContentNotBetween(String value1, String value2) {
            addCriterion("THE_CONTENT not between", value1, value2, "theContent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 19 20:42:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}