package com.jxufe.liuyf.fsv.common.bean;

import com.jxufe.liuyf.fsv.common.AbstractCacheTable;
import com.jxufe.liuyf.fsv.common.CacheIndex;
import org.codehaus.jackson.annotate.JsonIgnore;

public class InsUser extends AbstractCacheTable implements CacheIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS_USER.USER_ID
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS_USER.USER_NAME
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS_USER.PAY_PASSWORD
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    private String payPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS_USER.EMAIL_ADDRESS
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    private String emailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS_USER.ID_CARD_NUMBER
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    private String idCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS_USER.PHONE_NUMBER
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INS_USER.RECEIVE_ADDRESS
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    private String receiveAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS_USER.USER_ID
     *
     * @return the value of INS_USER.USER_ID
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS_USER.USER_ID
     *
     * @param userId the value for INS_USER.USER_ID
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS_USER.USER_NAME
     *
     * @return the value of INS_USER.USER_NAME
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS_USER.USER_NAME
     *
     * @param userName the value for INS_USER.USER_NAME
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS_USER.LOGIN_PASSWORD
     *
     * @return the value of INS_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS_USER.LOGIN_PASSWORD
     *
     * @param loginPassword the value for INS_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS_USER.PAY_PASSWORD
     *
     * @return the value of INS_USER.PAY_PASSWORD
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS_USER.PAY_PASSWORD
     *
     * @param payPassword the value for INS_USER.PAY_PASSWORD
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS_USER.EMAIL_ADDRESS
     *
     * @return the value of INS_USER.EMAIL_ADDRESS
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS_USER.EMAIL_ADDRESS
     *
     * @param emailAddress the value for INS_USER.EMAIL_ADDRESS
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS_USER.ID_CARD_NUMBER
     *
     * @return the value of INS_USER.ID_CARD_NUMBER
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public String getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS_USER.ID_CARD_NUMBER
     *
     * @param idCardNumber the value for INS_USER.ID_CARD_NUMBER
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public void setIdCardNumber(String idCardNumber) {
        this.idCardNumber = idCardNumber == null ? null : idCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS_USER.PHONE_NUMBER
     *
     * @return the value of INS_USER.PHONE_NUMBER
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS_USER.PHONE_NUMBER
     *
     * @param phoneNumber the value for INS_USER.PHONE_NUMBER
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INS_USER.RECEIVE_ADDRESS
     *
     * @return the value of INS_USER.RECEIVE_ADDRESS
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INS_USER.RECEIVE_ADDRESS
     *
     * @param receiveAddress the value for INS_USER.RECEIVE_ADDRESS
     *
     * @mbggenerated Fri Apr 13 16:32:05 CST 2018
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    @JsonIgnore
    @Override
    public String getIndex() {
        return getFullClassName(this) + getUserId();
    }
}