package com.jxufe.liuyf.dao.interfaces;

import com.jxufe.liuyf.fsv.common.bean.CfgBusinessCode;
import com.jxufe.liuyf.fsv.common.bean.CfgBusinessCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CfgBusinessCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int countByExample(CfgBusinessCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int deleteByExample(CfgBusinessCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int deleteByPrimaryKey(String busicode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int insert(CfgBusinessCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int insertSelective(CfgBusinessCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    List<CfgBusinessCode> selectByExample(CfgBusinessCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    CfgBusinessCode selectByPrimaryKey(String busicode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") CfgBusinessCode record, @Param("example") CfgBusinessCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int updateByExample(@Param("record") CfgBusinessCode record, @Param("example") CfgBusinessCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int updateByPrimaryKeySelective(CfgBusinessCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_BUSINESS_CODE
     *
     * @mbggenerated Mon Mar 19 20:50:43 CST 2018
     */
    int updateByPrimaryKey(CfgBusinessCode record);
}