package com.jxufe.liuyf.dao.interfaces;

import com.jxufe.liuyf.fsv.common.bean.CfgPageContent;
import com.jxufe.liuyf.fsv.common.bean.CfgPageContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfgPageContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    int countByExample(CfgPageContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    int deleteByExample(CfgPageContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    int insert(CfgPageContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    int insertSelective(CfgPageContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    List<CfgPageContent> selectByExample(CfgPageContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") CfgPageContent record, @Param("example") CfgPageContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CFG_PAGE_CONTENT
     *
     * @mbggenerated Thu Apr 19 20:42:51 CST 2018
     */
    int updateByExample(@Param("record") CfgPageContent record, @Param("example") CfgPageContentExample example);
}